name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run: docker build . --file Dockerfile --build-arg version=$(cat VERSION) --tag bitsler/docker-bitcoind:$(cat VERSION) --tag bitsler/docker-bitcoind:latest
    
    - name: Build the Docker Testnet image
      run: |
          cp Dockerfile DockerfileTest
          sed 's/8332 8333/18332 18333/g' DockerfileTest
          docker build . --file DockerfileTest --build-arg version=$(cat VERSION) --tag bitsler/docker-bitcoindtest:$(cat VERSION)
    
    - name: Log into registry
      run: echo "${{ secrets.HUB_TOKEN }}" | docker login -u ${{ secrets.HUB_USERNAME }} --password-stdin

    - name: Push image
      run: |
          docker push bitsler/docker-bitcoind:$(cat VERSION)
          docker push bitsler/docker-bitcoind:latest 
          docker push bitsler/docker-bitcoindtest:$(cat VERSION)
      
      
